using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;
using System.Collections.Generic;

namespace EduAIAPI.Models
{
    public class Topic
    {
        [BsonId]
        [BsonRepresentation(BsonType.ObjectId)]
        public string Id { get; set; } = ObjectId.GenerateNewId().ToString(); // Auto-generated by MongoDB

        [BsonElement("title")]
        public string Title { get; set; } = string.Empty;

        [BsonElement("description")]
        public string Description { get; set; } = string.Empty;

        [BsonElement("course")]
        public string Course { get; set; } = string.Empty; // Will be set programmatically

        [BsonElement("lectures")]
        public List<string> Lectures { get; set; } = new List<string>(); // Will be set programmatically
    }
}